controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints:
        - joint_1
        - joint_2

    position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - joint_1
        - joint_2

